export const productsData =[
  {
    name: 'Americano',
    image: 'https://picsum.photos/48',
    status: 'green',
    date: null,
  },
  {
    name: 'Espresso',
    image: 'https://picsum.photos/49',
    status: 'yellow',
    date: null,
  },
  {
    name: 'Mocha',
    image: '',
    status: 'green',
    date: null,
  },
  {
    name: 'White Mocha',
    image: '',
    status: 'yellow',
    date: 704305433,
  },
  {
    name: 'Latte',
    image: 'https://picsum.photos/12',
    status: 'green',
    date: 1666715033,
  },
  {
    name: 'Cappucino',
    image: 'https://picsum.photos/33',
    status: 'green',
    date: null,
  },
  {
    name: 'Walking with Giants',
    image: 'https://picsum.photos/64',
    status: 'green',
    date: null,
  },
  {
    name: 'Turbinator 2',
    image: 'https://picsum.photos/87',
    status: 'red',
    date: null,
  },
  {
    name: 'Super Cali Fragilistic Expialidocious',
    image: '',
    status: 'red',
    date: 704305433,
  },
  {
    name: 'Baseball Hat',
    image: 'https://picsum.photos/78',
    status: 'green',
    date: null,
  },
{
    name: 'Americano',
    image: 'https://picsum.photos/46',
    status: 'green',
    date: null,
  },
  {
    name: 'Espresso',
    image: 'https://picsum.photos/99',
    status: 'yellow',
    date: null,
  },
  {
    name: 'Mocha',
    image: '',
    status: 'green',
    date: null,
  },
  {
    name: 'White Mocha',
    image: '',
    status: 'yellow',
    date: 704305433,
  },
  {
    name: 'Latte',
    image: 'https://picsum.photos/43',
    status: 'green',
    date: 1666715033,
  },
  {
    name: 'Cappucino',
    image: 'https://picsum.photos/75',
    status: 'green',
    date: null,
  },
  {
    name: 'Walking with Giants',
    image: 'https://picsum.photos/97',
    status: 'green',
    date: null,
  },
  {
    name: 'Turbinator 2',
    image: 'https://picsum.photos/30',
    status: 'red',
    date: null,
  },
  {
    name: 'Super Cali Fragilistic Expialidocious',
    image: '',
    status: 'red',
    date: 704305433,
  },
  {
    name: 'Baseball Hat',
    image: 'https://picsum.photos/74',
    status: 'green',
    date: null,
  },

]
